# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# Don't enforce any particular name for block params
Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  # rspec is known as DSL with big blocks
  Exclude:
    - test/**/*

# do not break API
Naming/MethodParameterName:
  Enabled: false

AllCops:
  Exclude:
    - 'src/modules/**/*'
    - 'src/include/**/*'
    - 'testsuite/**/*'
    - 'src/clients/*'
    - '**/*.spec'
